Internal Server Error: /
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 212, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: inc/_pagination.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: inc/_pagination.html
"GET / HTTP/1.1" 500 156057
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 212, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: inc/_pagination.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: inc/_pagination.html
"GET / HTTP/1.1" 500 156194
