Internal Server Error: /
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 212, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: inc/_pagination.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: inc/_pagination.html
"GET / HTTP/1.1" 500 156057
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 212, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: inc/_pagination.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: inc/_pagination.html
"GET / HTTP/1.1" 500 156194
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 131: 'endfor'. Did you forget to register or load this tag?
"GET /?page=1 HTTP/1.1" 500 191046
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 80: 'else', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
"GET / HTTP/1.1" 500 234287
Internal Server Error: /add_product_photo/
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Internal Server Error: /add_product_photo/
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /add_product_photo/ HTTP/1.1" 500 136472
Internal Server Error: /add_product_photo/
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /add_product_photo/ HTTP/1.1" 500 136472
Internal Server Error: /add_product_photo/
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /add_product_photo/ HTTP/1.1" 500 136472
Internal Server Error: /add_product_photo/
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /add_product_photo/ HTTP/1.1" 500 136472
Internal Server Error: /auth/
Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Django_Egor\django_egor\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'static'. Did you forget to register or load this tag?
"GET /auth/ HTTP/1.1" 500 141060
